In [1]:
import pandas as pd

In [2]:
import pycaret

In [3]:
diabetes_data = pd.read_csv('diabetes.csv')

In [4]:
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
from pycaret.classification import *

In [6]:
classify_experiment = setup(diabetes_data,
                           target='Outcome',
                           log_experiment=True,
                           session_id=123,
                           experiment_name='diabetes_disease')

2022/06/30 14:51:00 INFO mlflow.tracking.fluent: Experiment with name 'diabetes_disease' does not exist. Creating a new experiment.

In [7]:
## comparing differnet models
compare_models()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
logistic=create_model('lr')

In [9]:
model=tune_model(logistic)

In [10]:
model

LogisticRegression(C=7.863, class_weight={}, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)