In [1]:
import pandas as pd

In [2]:
import pycaret

In [3]:
heart_data = pd.read_csv('heart.csv')

In [4]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
from pycaret.classification import *

In [6]:
classify_experiment = setup(heart_data,
                           target='target',
                           log_experiment=True,
                           session_id=123,
                           experiment_name='heart_disease')

In [7]:
## comparing differnet models
compare_models()

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=123, solver='auto',
                tol=0.001)

In [8]:
ridge = create_model('ridge')

In [9]:
ridge

RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, normalize=False, random_state=123, solver='auto',
                tol=0.001)

In [10]:
model=tune_model(ridge)